---

- name: My first playbook
  hosts: all
  tasks:
      - name: Afficher helloworld vide
        include_role:
          name: helloworld

      - name: Afficher helloworld du vrai createur
        include_role: 
          name: helloworld
        vars:
          helloworld_myname: dean
